config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  root to: 'pages#home'
  namespace :admin do
    resources :users
    resources :bookings
    resources :flats

    root to: "users#index"
  end
  devise_for :users
  resources :bookings, only: [:index, :show, :destroy]
  resources :flats do
    resources :bookings, only: [:new, :create]
  end
  resources :users do
    resources :messages, only: [:index, :create]
  end
  get 'my_flat', to: 'flats#my_flat'
  get 'conversations', to: 'messages#conversations'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date,   presence: true

  def total_nights
    (end_date - start_date).to_i
  end

  def total_price
    total_nights * flat.price
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  include PgSearch::Model
    pg_search_scope :search_by_description_and_address,
      against: [ :description, :address ],
      using: {
        tsearch: { prefix: true }
      }

  belongs_to :user
  has_many   :bookings, dependent: :destroy
  has_many_attached :images

  validates :address,     presence: true
  validates :surface,     presence: true, numericality: { only_integer: true }
  validates :price,       presence: true, numericality: { only_integer: true }
  validates :room,        presence: true, numericality: { only_integer: true }
  validates :description, presence: true
  validates :max_guests,  presence: true, numericality: { only_integer: true }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader

  def is_available?(start_date, end_date)
    bookings.each do |b|
      return false if (b.start_date..b.end_date).overlaps?(start_date.to_date..end_date.to_date)
    end
    return true
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender,   class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :content, length: { maximum: 100  }
end

app/models/review.rb
class Review < ApplicationRecord
  AUTHORIZED_CONTENT = ["Hote Excellent", "Hote très charmant", "Hote moyen", "L'hote peut s'améliorer"]
  validates  :content, inclusion: { in: AUTHORIZED_CONTENT }
  belongs_to :user
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats, dependent: :destroy
  has_many :bookings, dependent: :destroy

  def friends
    friends = Message.where(sender: self).map(&:receiver) + Message.where(receiver: self).map(&:sender)
    friends.uniq
  end

  def conversation_with(friend_id)
    friend       = User.find(friend_id)
    conversation = Message.where(sender: self, receiver: friend) + Message.where(sender: friend, receiver: self)
    conversation.sort_by(&:created_at)
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with name: ENV['ADMIN_LOGIN'], password: ENV['ADMIN_PASSWORD']
  end
end

app/controllers/admin/bookings_controller.rb
module Admin
  class BookingsController < Admin::ApplicationController
  end
end

app/controllers/admin/flats_controller.rb
module Admin
  class FlatsController < Admin::ApplicationController
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: [:create]
  before_action :set_booking, only: [:show, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(booking_params.merge(user: current_user))
    @booking.flat = @flat
    if @booking.save!
      redirect_to bookings_path
    else
      render :new
    end
  end

  def show
    @flat         = @booking.flat
    @total_nights = @booking.total_nights
    @total_price  = @booking.total_price
    @markers      = [{
      lat: @flat.latitude,
      lng: @flat.longitude
    }]
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    flats_filter = params[:flats_filter]
    @flats = Flat.where.not(latitude: nil, longitude: nil)
    if flats_filter.present?
      if flats_filter[:search].present?
        @flats = Flat.search_by_description_and_address(flats_filter[:search])
      end
      if flats_filter[:min_price].present?
        @flats = @flats.where("flats.price >= ?", flats_filter[:min_price])
      end
      if flats_filter[:max_price].present?
        @flats = @flats.where("flats.price <= ?", flats_filter[:max_price])
      end
      if flats_filter[:start_date].present? || flats_filter[:end_date].present?
        @flats = @flats.select { |flat| flat.is_available?(flats_filter[:start_date],flats_filter[:end_date]) }
      end
    end

    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "shared/infowindow", locals: { flat: flat })
      }
    end
  end

  def show
    @booking        = Booking.new
    @bookings       = @flat.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date
      }
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params.merge(user: current_user))
    if @flat.save!
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to my_flat_path
  end

  def my_flat
    @flats = current_user.flats
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:address, :surface, :description, :price, :room, :max_guests, images: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_messages, only: [:index, :create]
  before_action :set_friend,   only: [:index, :create]

  def conversations
    @users_with_conversation = current_user.friends
  end

  def index
    @message = Message.new
  end

  def create
    @message          = Message.new(message_params)
    @message.sender   = current_user
    @message.receiver = @friend
    if @message.save
      redirect_to user_messages_path(@message.receiver)
    else
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def set_messages
    @messages = current_user.conversation_with(params[:user_id])
  end

  def set_friend
    @friend = User.find(params[:user_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # This is a test for background jobs
    FakeJob.perform_later
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review         = Review.new(review_params)
    @booking        = Booking.find(params[:booking_id])
    @review.booking = @booking
    @review.user    = current_user
    @flat           = @review.booking.flat
    if @review.save
      redirect_to flat_path(@flat.id)
    else
      render "bookings/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <%= simple_form_for [flat, booking] do |f| %>
      <%= f.input :start_date, label: "Sélectionnez vos dates:", as: :string, required: false, input_html: { id: "range_start", class: "d-none"} %>
      <%= f.input :end_date, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none" } %>
      <p>Réservation pour <span id="total-nights">0</span> nuits</p>
      <p>Prix total : <span class="font-weight-bold"><span id="total-price">0</span> €</span></p>
      <%= f.submit text, class: 'btn btn-principal' %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="pages-container margin-nav">
  <h3>Mes réservations</h3>
  <div class="cards-grid-3">
    <% if @bookings.empty? %>
      <p>Pas de réservations</p>
      <%= link_to flats_path do %>
        <button class="btn btn-principal">Chercher un appart</button>
      <% end %>
    <% else %>
      <% @bookings.each do |booking| %>
        <div class="card-flat">
          <%= link_to booking_path(booking.id) do %>
            <div class="card-flat-image">
              <%= image_tag booking.flat.images.first, height: 300, width: 400, crop: :fill %>
            </div>
            <h5><%= booking.flat.address %></h5>
            <div class="card-flat-content">
              <div class="card-flat-date">
                <p>Du <%= booking.start_date.strftime('%e/%m/%Y')%></p>
                <p>au <%= booking.end_date.strftime('%e/%m/%Y')%></p>
              </div>
              <div>
                <%= link_to booking_path(booking.id) do %>
                  <button class="btn btn-principal btn-margin-top">Voir</button>
                <% end %>
                <%= link_to booking_path(booking),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <button class="btn btn-principal btn-margin-top">Annuler</button>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="main-container">

  <div class="book-container">
    <div class="show-title">
      <h2>Ma réservation</h2>
      <%= link_to bookings_path do %>
        <button class="btn btn-principal btn-margin-top">Toutes mes réservations</button>
      <% end %>
    </div>


    <div class="book-content">
      <%= image_tag @flat.images.first, height: 300, width: 400, crop: :fill %>
      <div class="book-info">
        <h3><%= @flat.address %></h3>
        <div class="book-date">
          <h5>Réservé :</h5>
          <h5>Du <%= @booking.start_date.strftime('%e %B %Y')%></h5>
          <h5>Au <%= @booking.end_date.strftime('%e %B %Y')%></h5>
        </div>
        <div class="book-price">
          <h3>Prix total : <%= @total_price %> €</h3>
        </div>
      </div>
    </div>
    <div class="book-description">
      <li><%= @flat.description %></li>
    </div>
    <%= link_to user_messages_path(@flat.user), class:"btn btn-principal btn-margin-top" do %>
      Contacter le propriétaire
    <% end %>
  </div>

  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/flats/_form.html.erb
<div class="container margin-nav">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <h1><%= text %></h1>
      <%= simple_form_for flat do |f| %>
        <%= f.input :address %>
        <%= f.input :description %>
        <div class="style-form-align">
          <%= f.input :surface, label: "Surface in m²" %>
          <%= f.input :room, collection: 0..10 %>
          <%= f.input :max_guests, collection: 0..20 %>
          <%= f.input :price, label: "Price in €" %>
        </div>
        <%= f.file_field :images, as: :file, multiple: true, class: "form-control" %>
        <%= f.submit "Valider", class: 'btn btn-principal' %>
      <% end %>
      <%= link_to "Revenir à mes apparts", my_flat_path %>
    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<%= render 'form', flat: @flat, text: "Modifier votre annonce" %>

app/views/flats/index.html.erb
<div class="main-container">

  <div class="cards-container">
    <div class="search">
      <%= simple_form_for :flats_filter, url: flats_path, method: :get do |f| %>
        <%= f.input :search, label: false,
                             input_html: { placeholder: "Champ de recherche" } %>
        <div class="row">
          <div class="col-12 col-md-6 col-lg-3">
            <%= f.input :min_price, label: false,
                                    input_html: { type: :number,
                                                  min: "0",
                                                  placeholder: "Prix mini" } %>
          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <%= f.input :max_price, label: false,
                                    input_html: { type: :number,
                                                  placeholder: "Prix max" } %>
          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <%= f.input :start_date, label: false,
                                     input_html: { type: :date } %>

          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <%= f.input :end_date, label: false,
                                   input_html: { type: :date } %>
          </div>
        </div>
        <%= f.submit "Chercher", class: "btn btn-principal mt-0" %>
      <% end %>
    </div>

    <div class="cards-grid-2">
      <% @flats.each do |flat| %>
        <%= link_to flat_path(flat.id) do %>
          <div class="card-flat">
            <div class="card-flat-image">
              <%= image_tag flat.images.first, height: 300, width: 400 %>
              <h4 class="card-flat-price"><%= flat.price %> €</h4>
            </div>
            <h5 class="card-flat-address"><%= flat.address %></h5>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/flats/my_flat.html.erb
<div class="pages-container margin-nav">
  <h3>Mes appartements</h3>
  <div class="cards-grid-3">
    <% if @flats.empty? %>
      <p>Pas encore d'appartements</p>
      <%= link_to new_flat_path do %>
        <button class="btn btn-principal">Publier une annonce</button>
      <% end %>

    <% else %>
      <% @flats.each do |flat| %>
        <div class="card-flat">
          <%= link_to edit_flat_path(flat.id) do %>
            <div class="card-flat-image">
              <%= image_tag flat.images.first, height: 300, width: 400, crop: :fill %>
            </div>
            <h5 class="card-flat-address"><%= flat.address %></h5>
            <%= link_to flat_path(flat.id) do %>
              <button class="btn btn-principal btn-margin-top">Voir</button>
            <% end %>
            <%= link_to edit_flat_path(flat.id) do %>
              <button class="btn btn-principal btn-margin-top">Editer</button>
            <% end %>
            <%= link_to flat_path(flat.id),
                method: :delete,
                data: { confirm: "Attention, la suppression est définitive" } do %>
              <button class="btn btn-principal btn-margin-top">Supprimer</button>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/flats/my_flats.html.erb
<h2>My flats</h2>

<div class="cards">
  <% @my_flats.each do |flat| %>
    <%= link_to flat_path(flat.id) do %>
      <div class="card">
        <li>address : <%= flat.address %></li>
        <li>room : <%= flat.room %></li>
        <li>surface : <%= flat.surface %></li>
        <li>price : <%= flat.price %></li>
        <li>max_guests : <%= flat.max_guests %></li>
      </div>
    <% end %>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat, text: "Publier une annonce" %>

app/views/flats/show.html.erb
<div class="flat-container margin-nav">
  <div class="flat-container-left">
    <div class="show-title flat">
      <h3><%= @flat.address %></h3>
      <%= link_to flats_path do %>
        <button class="btn btn-principal btn-margin-top">Tous les apparts</button>
      <% end %>
    </div>

    <div class="flat-content">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @flat.images.each_with_index do |image, index| %>
            <div class="carousel-item <%= "active" if index == 0%>">
              <%= image_tag image, height: 500, width: 830 %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div class="flat-description">
      <div class="flat-info">
        <p><i class="fas fa-bed"></i> <%= pluralize(@flat.room, 'chambre')%></p>
        <p><i class="fas fa-ruler-combined"></i> <%= @flat.surface %> m²</p>
        <p><i class="fas fa-euro-sign"></i><span id="flat-price-per-night"><%= @flat.price %></span> € / nuit</p>
        <p><i class="fas fa-users"></i> <%= @flat.max_guests %></p>
      </div>
      <p><%= @flat.description %></p>
    </div>
  </div>
  <div class="flat-calendar">
    <%= render 'bookings/form', booking: @booking, flat: @flat, text: "Réserver" %>
  </div>
  <div
    id="booking-form-div"
    data-bookings="<%= @bookings_dates.to_json %>"
  >
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="algolia-app-id" content="<%= ENV["ALGOLIA_APP_ID"] %>">
    <meta name="algolia-search-only-api-key" content="<%= ENV["ALGOLIA_API_KEY"] %>">
    <%= favicon_link_tag %>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' unless action_name == 'home' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/conversations.html.erb
<div class="pages-container margin-nav">
  <% if @users_with_conversation.empty? %>
    <h3>Vous n'avez pas de conversation</p>
  <% else %>
    <h3>Mes conversations</h3>
    <% @users_with_conversation.each do |user| %>
      <%= link_to user_messages_path(user) do %>
        <p>Conversation avec <%= user.first_name %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="pages-container margin-nav">
  <h3>Ma conversation avec <%= @friend.first_name %></h3>
  <% if @messages.empty? %>
    <p> Envoyer un message à <%= @friend.first_name %> </p>
  <% else %>
    <% @messages.each do |message| %>
      <ul>
        <li><p><%= message.sender.first_name %> dit : <%= message.content %></p></li>
      </ul>
    <% end %>
  <% end %>

    <%= simple_form_for [@friend, @message] do |f| %>
      <%= f.input :content %>
      <%= f.submit "Envoyer un message", class: "btn btn-primary" %>
    <% end %>

    <%= link_to 'Retour aux conversations', conversations_path %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/823694/pexels-photo-823694.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
  <div class="container text-center">
    <h1>Bienvenue!</h1>
    <p>Réservez des lieux uniques et vivez des experiences incroyables.</p>
    <%= form_tag flats_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control w-25 m-auto",
        placeholder: "Paris Montmartre"
      %>
      <%= submit_tag "Lancer la recherche", class: "btn btn-principal" %>
    <% end %>
  </div>
</div>

app/views/pages/my_flat.html.erb
<div class="dashboard-container margin-nav">
  <h3>My flats</h3>
  <% if @flats.empty? %>
    <p>No flat yet</p>
    <%= link_to new_flat_path do %>
      <button class="btn btn-principal">Add a flat now</button>
    <% end %>
  <% else %>
    <% @flats.each do |flat| %>
      <%= link_to flat_path(flat.id) do %>
        <div class="flat-card">
          <div class="flat-image">
            <%= cl_image_tag flat.photo, height: 200, width: 300, crop: :fill %>
          </div>
          <div class="flat-content">
            <li><%= flat.address %></li>
            <li><%= pluralize(flat.room, 'room')%></li>
            <li><%= flat.surface %> m²</li>
            <li><%= flat.price %> €</li>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_infowindow.html.erb
<%= link_to flat_path(flat) do %>
  <p><%= flat.price %></p>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to flats_path, class: "navbar-brand" do %>
    <%= image_tag("logo.png") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(flats_path) %>">
        <%= link_to "Rechercher", flats_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if current_page?(new_flat_path) %>">
          <%= link_to "Publier une annonce", new_flat_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(my_flat_path) %>">
          <%= link_to "Mes appartements", my_flat_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(bookings_path) %>">
          <%= link_to "Mes Voyages", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(conversations_path) %>">
          <%= link_to "Mes conversations", conversations_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://via.placeholder.com/100x100.png?text=Avatar", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", "#", class: "dropdown-item" %>
            <%= link_to "Editer mon profil", "#", class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</div>